CREATE TABLE [dbo].[Transaction]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FileId] INT NOT NULL,
	[RawData] NVARCHAR(MAX) NOT NULL,
	[KWOTA] INT NOT NULL, 
	[DATAOBCIAZENIARACHUNKU] DATE NOT NULL, 
	[RACHUNEKKLIENTAADRESATA] NVARCHAR(34) NOT NULL
)
